<?php

namespace BasicDashboard\Web\Currencies\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreCurrencyRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreCurrencyRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "rate" => "required",
        ];
    }

    public function messages(): array
    {
        return [
            'rate.required' => __('currency.rate_validation'),
        ];
    }
}
