<?php

namespace BasicDashboard\Web\Currencies\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateCurrencyRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateCurrencyRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "rate" => "required",
            "country_id" => "",
            "date" => "",
            "time" => "",
        ];
        
    }

    public function messages(): array
    {
        return[
            'rate.required' => __('currency.rate_validation'),
        ];
    }
}
