<?php

namespace BasicDashboard\Mobile\Countries\Services;

use BasicDashboard\Foundations\Domain\Countries\Repositories\CountryRepositoryInterface;
use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Countries\Resources\CountryResource;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A CountryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CountryService extends BaseMobileController
{
    const INDEX_SUCCESS = "Index success";
    const DETAIL_SUCCESS = "Detail success";

    public function __construct(
        private CountryRepositoryInterface $countryRepository,
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): JsonResponse
    {
        $data = $this->countryRepository->getCountryList($request);
        $data = CountryResource::collection($data)->response()->getData(true);
        return $this->sendResponse(self::INDEX_SUCCESS, $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(array $request): JsonResponse
    {
        try {
            $this->countryRepository->beginTransaction();
            $data = $this->countryRepository->edit($request['id']);
            $data = new CountryResource($data);
            $data = $data->response()->getData(true)['data'];
            $this->countryRepository->commit();
            return $this->sendResponse(self::DETAIL_SUCCESS, $data);
        } catch (Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
