<?php

namespace BasicDashboard\Web\Audits\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateAuditRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateAuditRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }
}
