<?php

namespace BasicDashboard\Web\Articles\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        $this->thumbnail ??= '/Default/default_article_pic.jpg';
        return [
            "id" => customEncoder($this->id),
            "title" => $this->title,
            "type" => $this->type,
            'description' => $this->description,
            'show_thumbnail' => $this->show_thumbnail,
            'keywords' => $this->keywords,
            'category' => $this->category->name,
            'link' => $this->link ? retrievePublicFiles($this->link) : [],
            'subcategory' => $this->subcategory->name,
            'is_published' => $this->is_published,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            'created_at' => $this->created_at ? date('d M Y h:i A', strtotime($this->created_at)) : null,
        ];
    }
}
