<?php

namespace BasicDashboard\Web\Articles\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        $this->thumbnail ??= '/Default/default_article_pic.jpg';
        return [
            "id" => customEncoder($this->id),
            "title" => $this->title,
            'title_other' => $this->title_other,
            "type" => $this->type,
            'description' => $this->description,
            "description_other" => $this->description_other,
            'category' => $this->category->name,
            'subcategory' => $this->subcategory->name,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            'createdBy' => $this->createdBy->name,
            'createdByNumber' => $this->createdBy->phone,
            'writtenBy' => $this->writtenBy->name,
            "is_published" => $this->is_published,
            "is_banner" => $this->is_banner,
            "is_highlighed" => $this->is_highlighed,
            "site_url" => $this->site_url,
            "tags" => $this->tags,
            "total_view_count" => $this->total_view_count,
            "date" => $this->is_published ?? $this->date ? date('d M Y', strtotime($this->date)) : null,
            "link" => retrievePublicFiles($this->link),
            'created_at' => $this->created_at ? date('d M Y h:i A', strtotime($this->created_at)) : null,
        ];
    }
}
