<?php

namespace BasicDashboard\Web\Sports\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Sports\Services\SportService;
use BasicDashboard\Web\Sports\Validation\StoreSportRequest;
use BasicDashboard\Web\Sports\Validation\UpdateSportRequest;
use BasicDashboard\Web\Sports\Validation\DeleteSportRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A SportController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SportController extends BaseController
{
    public function __construct(
        private SportService $sportService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->sportService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->sportService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreSportRequest $request): RedirectResponse
    {
        return $this->sportService->store($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->sportService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->sportService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateSportRequest $request, string $id): RedirectResponse
    {
        return $this->sportService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteSportRequest $request): RedirectResponse
    {
        return $this->sportService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
