<?php

namespace BasicDashboard\Mobile\Notifications\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A NotificationResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class NotificationResource extends JsonResource
{
    public function toArray($request):array
    {
        $this->uploaded_photo ??= '/Default/default_notification_image.png';
        return [
            "id" => customEncoder($this->id),
            "title" => $this->title,
            "body" => $this->body,
            'uploaded_photo' => retrievePublicFile($this->uploaded_photo),
            "uploaded_video" => $this->uploaded_video ? retrievePublicFile($this->uploaded_video) : null,
            "created_at" => $this->created_at->format('Y-m-d')
        ];
    }
}
