<?php

namespace BasicDashboard\Web\Settings\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreSettingRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreSettingRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "key" => "required",
            "value" => "required",
        ];
    }
}
