<?php

namespace BasicDashboard\Web\Settings\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateSettingRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateSettingRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "key"=>"required",
          "value"=>"required",
        ];
    }
}
