<?php

namespace BasicDashboard\Foundations\Domain\Categories\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\Categories\Category;
use BasicDashboard\Foundations\Domain\Categories\Repositories\CategoryRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A CategoryRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryRepository extends BaseRepository implements CategoryRepositoryInterface
{
    public function __construct(Category $model)
    {
        parent::__construct($model);
    }

    public function filterCategory(array $params): Builder | Category
    {
        $connection = $this->connection();
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('name', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('name_other', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('description', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('description_other', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getCategoryList($params): LengthAwarePaginator
    {
        return $this->filterCategory($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }

    //Mobile Section
    public function getCategoryListForMobile(): Collection
    {
        return $this->connection(true)->with('subcategories')->get();
    }

    //Spa Section
    public function getCategories(): Collection
    {
        return $this->connection(true)->with(['articles' => function ($query) {
            $query->limit(7);
        }])->get();
    }

    public function getCategoryListForSpa(): Collection
    {
        return $this->connection(true)->with('subcategories')->get();
    }

    public function getCategoryListForSpaFooter(): Collection
    {
        return $this->connection()->withCount('articles')->whereNot('id', 1)->get();
    }

    public function getCategoryListForHome(): Collection
    {
        return $this->connection()->whereNot('id', 1)->get();

    }

}
