<?php

namespace BasicDashboard\Foundations\Domain\Subcategories;
use App\Observers\AuditObserver;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use BasicDashboard\Foundations\Domain\categories\Category;

/**
 *
 * A Subcategory is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
#[ObservedBy([AuditObserver::class])]
class Subcategory extends Model
{
    use HasFactory, SoftDeletes;
      //protected $table = 'table_name';
      protected $guarded = [

    ];

    public function category() :BelongsTo
    {
      return $this->belongsTo(Category::class)->withDefault([
        'name' => '---'
      ]);
    }

}
