<?php

namespace BasicDashboard\Mobile\Articles\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        $this['thumbnail'] ??= '/Default/default_article_pic.jpg';
        $checkMedia = $this->link != [] && count($this->link) > 0;
        $banner_media = $checkMedia ? retrievePublicFile($this->link[0]) : null;
        return [
            "id" => customEncoder($this->id, 10003),
            "title" => $this->title,
            "title_other" => $this->title_other,
            "description" => $this->description == '<p><br></p>' ? '' : $this->description,
            "description_other" => $this->description_other == '<p><br></p>' ? '' : $this->description_other,
            "type" => $this->type,
            "category_id" => $this->category ? customEncoder($this->category->id) : '',
            "subcategory_id" => $this->subcategory->id ? customEncoder($this->subcategory->id) : '',
            "category_name" => $this->category?->name,
            "subcategory_name" => $this->subcategory?->name,
            "category_name_other" => $this->category?->name_other,
            "subcategory_name_other" => $this->subcategory?->name_other,
            "is_banner" => $this->is_banner,
            "writtenBy" => $this->writtenBy->name,
            "is_published" => $this->is_published,
            "is_highlighed" => $this->is_highlighed,
            "site_url" => "https://buddhist.news/articles/" . $this->id,
            "tags" => $this->tags ? explode(',', $this->tags) : null,
            "total_view_count" => $this->total_view_count,
            "date" => $this->date ? date('Y-m-d', strtotime($this->date)) : null,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            "link" => retrievePublicFiles($this->link),
            'banner_media' => $banner_media,
        ];
    }
}
