<?php

namespace BasicDashboard\Web\SponsorAds\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SponsorAdResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SponsorAdResource extends JsonResource
{
    public function toArray($request): array
    {
        $thumbnail = $this->thumbnail_image ? $this->thumbnail_image : "/Default/default_profile_pic.jpg";
        return [
            "id" => customEncoder($this->id),
            "name" => $this->name,
            "description" => $this->description,
            'thumbnail_image' => retrievePublicFile($thumbnail),
            'uploaded_video' => $this->uploaded_video ? retrievePublicFile($this->uploaded_video) : null,
            'org_uploaded_video' => $this->uploaded_video,
            'link' => $this->link,
            "start_date" => $this->start_date,
            "end_date" => $this->end_date,
            "position" => $this->position,
            "status" => $this->status,
            "countSponsorrate" => $this->countSponsorrate,
            "size" => $this->size,
            "platform" => $this->platform,
        ];
    }
}
