<?php

namespace BasicDashboard\Spa\Articles\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleResource extends JsonResource
{
    public function toArray($request):array
    {
        $this['thumbnail'] ??= '/Default/default_article_pic.jpg';
        return [
            "id" => $this->id,
            "title" => $this->title,
            "description" => $this->description == '<p><br></p>' ? '' : $this->description,
            "type" => $this->type,
            "keywords" => $this->keywords,
            'show_thumbnail' => $this->show_thumbnail,
            "category_id" => $this->category_id,
            "date" => $this->created_at->diffForHumans(),
            "category_name" => $this->category?->name,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            "link" => retrievePublicFiles($this->link),
        ];
    }
}
