<?php

namespace BasicDashboard\Spa\Articles\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class HomeArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        $this['thumbnail'] ??= '/Default/default_article_pic.jpg';

        return [
            "id" => $this->id,
            "title" => $this->title,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            "category_name" => $this->category?->name,
            "date" => $this->created_at->diffForHumans(),
            "subcategory_name" => $this->subcategory?->name,
        ];
    }
}
