<?php

namespace BasicDashboard\Spa\Articles\Resources;

use Carbon\Carbon;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A ArticleResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SiteMapArticleResource extends JsonResource
{
    public function toArray($request): array
    {
        $this['thumbnail'] ??= '/Default/default_article_pic.jpg';

        return [
            "id" => $this->id,
            "title" => $this->title,
            "slug" => $this->slug,
            "thumbnail" => retrievePublicFile($this->thumbnail),
            "updated_at" => $this->updated_at
        ];
    }
}
