<?php

namespace BasicDashboard\Web\ContactForms\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\ContactForms\Services\ContactFormService;
use BasicDashboard\Web\ContactForms\Validation\StoreContactFormRequest;
use BasicDashboard\Web\ContactForms\Validation\UpdateContactFormRequest;
use BasicDashboard\Web\ContactForms\Validation\DeleteContactFormRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A ContactFormController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ContactFormController extends BaseController
{
    public function __construct(
        private ContactFormService $contactFormService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->contactFormService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->contactFormService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreContactFormRequest $request): RedirectResponse
    {
        return $this->contactFormService->store($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->contactFormService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->contactFormService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateContactFormRequest $request, string $id): RedirectResponse
    {
        return $this->contactFormService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteContactFormRequest $request): RedirectResponse
    {
        return $this->contactFormService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
