<?php

namespace BasicDashboard\Web\Currencies\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A CurrencyResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CurrencyResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" => customEncoder($this->id),
            "rate"=>$this->rate,
            "country_id" =>$this->country_id,
            "date"=>$this->date,
            "time"=>$this->time,
        ];
    }
}
