<?php

namespace BasicDashboard\Mobile\Subcategories\Services;

use BasicDashboard\Foundations\Domain\Subcategories\Repositories\SubcategoryRepositoryInterface;
use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Subcategories\Resources\SubcategoryResource;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A SubcategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SubcategoryService extends BaseMobileController
{
    const INDEX_SUCCESS = "Index success";
    const DETAIL_SUCCESS = "Detail success";

    public function __construct(
        private SubcategoryRepositoryInterface $subcategoryRepository,
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(array $request): JsonResponse
    {
        $data = $this->subcategoryRepository->edit($request['id']);
        $data = new SubcategoryResource($data);
        $data = $data->response()->getData(true)['data'];
        return $this->sendResponse(self::DETAIL_SUCCESS, $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function getSubCategories(array $request): JsonResponse
    {
        try {
            $this->subcategoryRepository->beginTransaction();
            $data = $this->subcategoryRepository->getSubcategories($request);
            $data = SubcategoryResource::collection($data)->response()->getData(true);
            $this->subcategoryRepository->commit();
            return $this->sendResponse(self::INDEX_SUCCESS, $data['data']);
        } catch (Exception $e) {
            return $this->sendError($e->getMessage());
        }

    }
}
