<?php

namespace BasicDashboard\Web\Currencies\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Currencies\Services\CurrencyService;
use BasicDashboard\Web\Currencies\Validation\StoreCurrencyRequest;
use BasicDashboard\Web\Currencies\Validation\UpdateCurrencyRequest;
use BasicDashboard\Web\Currencies\Validation\DeleteCurrencyRequest;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

/**
 *
 * A CurrencyController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CurrencyController extends BaseController
{
    public function __construct(
        private CurrencyService $currencyService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->currencyService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->currencyService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreCurrencyRequest $request): RedirectResponse
    {
        // dd($request);
        return $this->currencyService->store($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->currencyService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->currencyService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateCurrencyRequest $request, string $id): RedirectResponse
    {
        return $this->currencyService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteCurrencyRequest $request): RedirectResponse
    {
        return $this->currencyService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
