<?php

namespace BasicDashboard\Spa\Sports\Resources;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SportResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SportShowResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "name"=>$this->name,
            "slug"=>$this->slug,
            "status"=> $this->status?->label(),
            "image"=>$this->image ? Storage::url($this->image):null,
            "description"=>$this->description,
            "link" => $this->link,
            "date" => $this->date && $this->time ? \Carbon\Carbon::parse($this->date . ' ' . $this->time)->diffForHumans() : null,
        ];
    }
}
