<?php

namespace BasicDashboard\Web\Settings\Services;

use BasicDashboard\Foundations\Domain\Settings\Repositories\Eloquent\SettingRepository;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Settings\Resources\SettingResource;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use Exception;

/**
 *
 * A SettingService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SettingService extends BaseController
{
    const VIEW = 'admin.setting';
    const ROUTE = 'settings';
    const LANG_PATH = "setting.setting";

    public function __construct(
        private SettingRepository $settingRepository,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): View
    {
        $settingList = $this->settingRepository->getSettingList($request);
        $settingList = SettingResource::collection($settingList)->response()->getData(true);
        return $this->returnView(self::VIEW.".index", $settingList, $request);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return view(self::VIEW.'.create');
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store($request): RedirectResponse
    {
        try {
            $this->settingRepository->beginTransaction();
            $this->settingRepository->insert($request);
            $this->settingRepository->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_created'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->settingRepository, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        $setting = $this->settingRepository->edit($id);
        $setting = new SettingResource($setting);
        $setting = $setting->response()->getData(true)['data'];
        return $this->returnView(self::VIEW . ".edit", $setting);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        $setting = $this->settingRepository->show($id);
        $setting = new SettingResource($setting);
        $setting = $setting->response()->getData(true)['data'];
        return $this->returnView(self::VIEW . '.show', $setting);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update($request, string $id): RedirectResponse
    {
         try {
            $this->settingRepository->beginTransaction();
            $this->settingRepository->update($request, $id);
            $this->settingRepository->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_updated'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->settingRepository, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy($request): RedirectResponse
    {
         try {
            $this->settingRepository->beginTransaction();
            $this->settingRepository->delete($request['id']);
            $this->settingRepository->commit();
            return $this->redirectRoute(self::ROUTE . ".index", __(self::LANG_PATH . '_deleted'));
        } catch (Exception $e) {
            return $this->redirectBackWithError($this->settingRepository, $e);
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
