<?php
namespace BasicDashboard\Foundations\Domain\Addresses\Repositories;

use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A AddressRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface AddressRepositoryInterface
{
    public function getAddressList($params): LengthAwarePaginator;
}
