<?php

namespace BasicDashboard\Mobile\Notifications\Controllers;

use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Notifications\Services\NotificationService;
use BasicDashboard\Mobile\Notifications\Validation\NotificationDetailRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A NotificationController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class NotificationController extends BaseMobileController
{
    public function __construct(
        private NotificationService $notificationService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->notificationService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////


    public function show(NotificationDetailRequest $request): JsonResponse
    {
        return $this->notificationService->show($request->validated()['id']);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

}
