<?php

namespace BasicDashboard\Spa\Sports\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteSportRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class IndexSportRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "date" => "nullable|date",
            "page" => "nullable|integer",
            "limit" => "nullable|integer",
        ];
    }
}
