<?php

namespace BasicDashboard\Mobile\Auth\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A AuthResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuthResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            "id" => customEncoder($this->id),
            "name" => $this->name,
            "email" => $this->email,
            "oauth_id" => $this->oauth_id,
            "oauth_provider" => $this->oauth_provider,
        ];
    }
}
