<?php

namespace BasicDashboard\Spa\Pages\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A PageResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageFooterResource extends JsonResource
{
    public function toArray($request):array
    {
        return [
            "title"=>$this->title,
            'title_other' => $this->title_other,
            "slug" => $this->slug,
        ];
}
}
