<?php

namespace BasicDashboard\Spa\Pages\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A PageResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageResource extends JsonResource
{
    public function toArray($request):array
    {
        return [
            "id" =>customEncoder($this->id),
            "title"=>$this->title,
            'title_other' => $this->title_other,
            "slug" => $this->slug,
            "type" => $this->type,
            "description" => $this->description == '<p><br></p>' ? '' : $this->description,
            "description_other" => $this->description_other == '<p><br></p>' ? '' : $this->description_other,
            "link" => retrievePublicFiles($this->link),
        ];
}
}
