<?php

namespace BasicDashboard\Spa\Articles\Controllers;

use BasicDashboard\Spa\Articles\Services\ArticleService;
use BasicDashboard\Spa\Articles\Validation\ArticleDetailRequest;
use BasicDashboard\Spa\Articles\Validation\GetArticlesRequest;
use BasicDashboard\Spa\Common\BaseSpaController;
use Illuminate\Http\JsonResponse;

/**
 *
 * A ArticleController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleController extends BaseSpaController
{
    public function __construct(
        private ArticleService $articleService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(GetArticlesRequest $request): JsonResponse
    {
        return $this->articleService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(ArticleDetailRequest $request): JsonResponse
    {
        return $this->articleService->show($request->id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function addViewCount(ArticleDetailRequest $request): JsonResponse
    {
        return $this->articleService->addViewCount($request->id);
    }

    public function homeIndex(): JsonResponse
    {
        return $this->articleService->homeIndex();
    }

    public function homeCategory(GetArticlesRequest $request): JsonResponse
    {
        return $this->articleService->homeCategory($request->validated());
    }
}
