<?php
namespace BasicDashboard\Web\Articles\Validation;

use Carbon\Carbon;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreArticleRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreArticleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->offsetUnset('_token');
    }

    public function rules(): array
    {
        return [
            "title"               => "required|max:255",
            "category_id"         => "required",
        ];
    }
    protected function passedValidation(): void
    {

    }

}
