<?php
namespace BasicDashboard\Web\Articles\Validation;

use Carbon\Carbon;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreArticleRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreArticleRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->offsetUnset('_token');
    }

    public function rules(): array
    {
        return [
            "title"               => "required|max:255",
            "category_id"         => "required",
            "is_sent_to_telegram" => "",
        ];
    }
    protected function passedValidation(): void
    {
        if ($this->date != null) {
            $this->merge([
                'date' => transform($this->date, fn() => Carbon::createFromFormat('m/d/Y', $this->date)->format('Y-m-d'))
                . ' ' . $this->time . ':00',
            ]);
        }
        $this->merge([
            'is_banner'     => 1,
            'is_highlighed' => 1,
        ]);
        $this->offsetUnset('time');
    }

}
