<?php

namespace BasicDashboard\Web\Subcategories\Controllers;

use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Subcategories\Services\SubcategoryService;
use BasicDashboard\Web\Subcategories\Validation\DeleteSubcategoryRequest;
use BasicDashboard\Web\Subcategories\Validation\StoreSubcategoryRequest;
use BasicDashboard\Web\Subcategories\Validation\UpdateSubcategoryRequest;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 *
 * A SubcategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SubcategoryController extends BaseController
{
    public function __construct(
        private SubcategoryService $subcategoryService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->subcategoryService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->subcategoryService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreSubcategoryRequest $request): RedirectResponse
    {
        return $this->subcategoryService->store($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->subcategoryService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->subcategoryService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateSubcategoryRequest $request, string $id): RedirectResponse
    {
        return $this->subcategoryService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteSubcategoryRequest $request): RedirectResponse
    {
        return $this->subcategoryService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
