<?php

namespace BasicDashboard\Spa\SponsorAds\Services;

use BasicDashboard\Foundations\Domain\SponsorAds\Repositories\Eloquent\SponsorAdRepository;
use BasicDashboard\Foundations\Domain\SponsorAds\Repositories\SponsorAdRepositoryInterface;
use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\SponsorAds\Resources\SponsorAdResource;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A SponsorAdService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SponsorAdService extends BaseSpaController
{

    public function __construct(
        private SponsorAdRepositoryInterface $sponsorAdRepositoryInterface,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): JsonResponse
    {
        $data = $this->sponsorAdRepositoryInterface->getSponsorAdList($request);
        $data = SponsorAdResource::collection($data)->response()->getData(true);
        return $this->sendResponse("Index success", $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): JsonResponse
    {
        $data = $this->sponsorAdRepositoryInterface->edit($id);
        $data= new SponsorAdResource($data);
        $data= $data->response()->getData(true)['data'];
        return $this->sendResponse('Show success',$data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
