<?php

namespace BasicDashboard\Web\Sports\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateSportRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateSportRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
            "slug"=>"required",
            "image"=>"",
            "status" => "",
            "description"=>"required",
            "date" => "required",
            "time" => "required",
            "link" => "required",
        ];
    }
}
