<?php
namespace BasicDashboard\Foundations\Domain\Categories\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use BasicDashboard\Foundations\Domain\Categories\Category;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Collection;

/**
 *
 * A CategoryRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface CategoryRepositoryInterface extends BaseRepositoryInterface
{
    public function filterCategory(array $params): Builder | Category;
    public function getCategoryList($params): LengthAwarePaginator;
    //Mobile Section
    public function getCategories(): Collection;
    public function getCategoryListForMobile(): Collection;
    public function getCategoryListForSpa(): Collection;

    public function getCategoryListForSpaFooter(): Collection;
    public function getCategoryListForHome(): Collection;

}
