<?php

namespace BasicDashboard\Mobile\Auth\Controllers;

use BasicDashboard\Mobile\Auth\Services\AuthService;
use BasicDashboard\Mobile\Auth\Validation\UserRegistrationSuccessRequest;
use BasicDashboard\Mobile\Common\BaseMobileController;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 *
 * A AuthController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuthController extends BaseMobileController
{
    public function __construct(
        private AuthService $authService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function registrationSuccess(UserRegistrationSuccessRequest $request): JsonResponse
    {
        return $this->authService->registrationSuccess($request->all());

    }

    public function checkAppVersion()
    {
        return $this->authService->checkAppVersion();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function idEncrypt(Request $request)
    {
        return customEncoder($request->id);
    }

    public function idDecrypt(Request $request)
    {
        return customDecoder($request->id);
    }

}
