<?php

namespace BasicDashboard\Mobile\Auth\Validation;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Hash;

/**
 *
 * A UserRegistrationSuccessRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UserRegistrationSuccessRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'name' => '',
            'email' => '',
            'oauth_id' => '',
            'oauth_provider' => '',
            'password' => '',
            'level' => '',
        ];
    }

    protected function passedValidation(): void
    {
        $this->merge([
            'password' => Hash::make(config('numbers.default_password')),
            'level' => config('config.level.user'),
        ]);
    }
}
