<?php

namespace BasicDashboard\Spa\SponsorAds\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SponsorAdResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SponsorAdResource extends JsonResource
{
    public function toArray($request):array
    {
        $this['thumbnail_image'] ??= '/Default/default_profile_pic.jpg';
        
        return [
            "id" => customEncoder($this->id),
            "name" => $this->name,
            "description" => $this->description,
            "thumbnail_image" => retrievePublicFile($this->thumbnail_image),
            "uploaded_video" => $this->uploaded_video ?  retrievePublicFile($this->thumbnail_image) : null,
            "start_date" => $this->start_date,
            "end_date" => $this->end_date,
            "position" => $this->position,
            "link" => $this->link,
            "status" => $this->status,
            "countSponsorrate"=>$this->countSponsorrate,
            "size"=>$this->size,
        ];
    }
}
