<?php
namespace BasicDashboard\Foundations\Domain\Settings\Repositories;

use Illuminate\Database\Eloquent\Collection as EloquentCollection;
use Illuminate\Support\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A SettingRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface SettingRepositoryInterface
{
    public function getSettingList($param): LengthAwarePaginator;
    public function getAppVersions() : Collection;
    public function getSocialAcc() : EloquentCollection;
}
