<?php

namespace BasicDashboard\Foundations\Domain\Countries;

use App\Observers\AuditObserver;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 *
 * A Country is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
#[ObservedBy([AuditObserver::class])]
class Country extends Model
{
    use HasFactory, SoftDeletes;
    //protected $table = 'table_name';
    protected $guarded = [];
    
    protected $casts = [
        'status' => 'boolean'
      ];
}
