<?php

namespace BasicDashboard\Web\Audits\Controllers;

use BasicDashboard\Web\Audits\Services\AuditService;
use BasicDashboard\Web\Common\BaseController;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 *
 * A AuditController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditController extends BaseController
{
    public function __construct(
        private AuditService $auditService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->auditService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->auditService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
