<?php
namespace BasicDashboard\Foundations\Domain\Pages\Repositories;

use Illuminate\Database\Eloquent\Collection;
use BasicDashboard\Foundations\Domain\Pages\Page;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;

/**
 *
 * A PageRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface PageRepositoryInterface extends BaseRepositoryInterface
{
    public function filterPage(array $params): Builder | Page;
    public function getPageList($params): LengthAwarePaginator;
    public function getDetailForSpa(): Collection;
}
