<?php

namespace BasicDashboard\Mobile\Subcategories\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A GetSubcategoriesRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class GetSubcategoriesRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'category_id' => '',
        ];
    }

}
