<?php

namespace BasicDashboard\Spa\Pages\Controllers;

use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\Pages\Services\PageService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A PageController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageController extends BaseSpaController
{
    public function __construct(
        private PageService $pageService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->pageService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////


    public function show(): JsonResponse
    {
        return $this->pageService->show();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function footerIndex() : JsonResponse
    {
        return $this->pageService->footerIndex();
    }

}
