<?php

namespace BasicDashboard\Web\Settings\Controllers;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Settings\Services\SettingService;
use BasicDashboard\Web\Settings\Validation\StoreSettingRequest;
use BasicDashboard\Web\Settings\Validation\DeleteSettingRequest;
use BasicDashboard\Web\Settings\Validation\UpdateSettingRequest;

/**
 *
 * A SettingController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SettingController extends BaseController
{
    public function __construct(
        private SettingService $settingService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->settingService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->settingService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreSettingRequest $request): RedirectResponse
    {
        return $this->settingService->store($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->settingService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->settingService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateSettingRequest $request, string $id): RedirectResponse
    {
        return $this->settingService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteSettingRequest $request): RedirectResponse
    {
        return $this->settingService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
