<?php

namespace BasicDashboard\Web\Countries\Controllers;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Countries\Services\CountryService;
use BasicDashboard\Web\Currencies\Services\CurrencyService;
use BasicDashboard\Web\Countries\Validation\StoreCountryRequest;
use BasicDashboard\Web\Countries\Validation\DeleteCountryRequest;
use BasicDashboard\Web\Countries\Validation\UpdateCountryRequest;

/**
 *
 * A CountryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CountryController extends BaseController
{
    public function __construct(
        private CountryService $countryService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->countryService->index($request->all());
        
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->countryService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreCountryRequest $request): RedirectResponse
    {
        return $this->countryService->store($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->countryService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id,Request $request): View | RedirectResponse
    {
        return $this->countryService->show($id,$request);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateCountryRequest $request, string $id): RedirectResponse
    {
        return $this->countryService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteCountryRequest $request): RedirectResponse
    {
        return $this->countryService->destroy($request->all());
    }
}
