<?php

namespace BasicDashboard\Spa\Categories\Resources;

use BasicDashboard\Spa\Articles\Resources\HomeArticleResource;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A CategoryResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class HomeCategoryResource extends JsonResource
{
    public function toArray($request): array
    {
        return [
            "id" => customEncoder($this->id, 10003),
            "name" => $this->name,
            "name_other" => $this->name_other,
            "articles" => HomeArticleResource::collection($this->articles),
        ];
    }
}
