<?php

namespace BasicDashboard\Spa\Categories\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A CategoryResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PureCategoryResource extends JsonResource
{
    private $colorCode;
    public function __construct($resource)
    {
        parent::__construct($resource);
        $colorName = 'category-color.' . trim($this->name) . '_color';
        $this->colorCode = config($colorName);
    }

    public function toArray($request): array
    {
        return [
            "id" => customEncoder($this->id, 10001),
            "name" => $this->name,
            "name_other" => $this->name_other,
            "color_code" => $this->colorCode,
        ];
    }
}
