<?php

namespace BasicDashboard\Mobile\Countries\Controllers;

use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Countries\Services\CountryService;
use BasicDashboard\Mobile\Countries\Validation\CountryDetailRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 *
 * A CountryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CountryController extends BaseMobileController
{
    public function __construct(
        private CountryService $countryService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->countryService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(CountryDetailRequest $request): JsonResponse
    {
        return $this->countryService->detail($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

}