<?php
namespace BasicDashboard\Foundations\Domain\Sports\Repositories;

use BasicDashboard\Foundations\Domain\Base\Repositories\BaseRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;
use BasicDashboard\Foundations\Domain\Sports\Sport;


/**
 *
 * A SportRepositoryInterface is declaration of methods inside of Repository.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

interface SportRepositoryInterface extends BaseRepositoryInterface
{
    public function filterSport(array $params): Builder | Sport;
    public function getSportList($params): LengthAwarePaginator;
}