<?php

namespace BasicDashboard\Web\Addresses\Controllers;

use Illuminate\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use BasicDashboard\Web\Common\BaseController;
use BasicDashboard\Web\Addresses\Services\AddressService;
use BasicDashboard\Web\Addresses\Validation\StoreAddressRequest;
use BasicDashboard\Web\Addresses\Validation\DeleteAddressRequest;
use BasicDashboard\Web\Addresses\Validation\UpdateAddressRequest;

/**
 *
 * A AddressController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AddressController extends BaseController
{
    public function __construct(
        private AddressService $addressService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): View
    {
        return $this->addressService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function create(): View
    {
        return $this->addressService->create();
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function store(StoreAddressRequest $request): RedirectResponse
    {
        return $this->addressService->store($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function edit(string $id): View | RedirectResponse
    {
        return $this->addressService->edit($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        return $this->addressService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function update(UpdateAddressRequest $request, string $id): RedirectResponse
    {
        return $this->addressService->update($request->validated(), $id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function destroy(DeleteAddressRequest $request): RedirectResponse
    {
        return $this->addressService->destroy($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
