<?php

namespace BasicDashboard\Spa\ContactForm\Controllers;

use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\ContactForm\Services\ContactFormService;
use BasicDashboard\Spa\ContactForm\Validation\StoreContactFormRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A ContactFormController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ContactFormController extends BaseSpaController
{
    public function __construct(
        private ContactFormService $contactFormService
    ) {
    }

    public function store(StoreContactFormRequest $request): JsonResponse
    {
        return $this->contactFormService->store($request->validated());
    }


}
