<?php

namespace BasicDashboard\Foundations\Domain\Pages\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\Pages\Repositories\PageRepositoryInterface;
use BasicDashboard\Foundations\Domain\Pages\Page;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A PageRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageRepository extends BaseRepository implements PageRepositoryInterface
{
    public function __construct(Page $model)
    {
        parent::__construct($model);
    }

    public function filterPage(array $params): Builder | Page
    {
        $connection = $this->connection()->with(['writtenBy','createdBy']);
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('title', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getPageList($params): LengthAwarePaginator
    {
        return $this->filterPage($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }

    public function getDetailForSpa(): Collection
    {
        return $this->connection()
            ->whereIn('slug',['about','privacy_policy','funding'])
            ->get();
    }
}
