<?php

namespace BasicDashboard\Mobile\Articles\Controllers;

use BasicDashboard\Mobile\Articles\Services\ArticleService;
use BasicDashboard\Mobile\Articles\Validation\ArticleDetailRequest;
use BasicDashboard\Mobile\Articles\Validation\GetArticlesRequest;
use BasicDashboard\Mobile\Common\BaseMobileController;
use Illuminate\Http\JsonResponse;

/**
 *
 * A ArticleController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class ArticleController extends BaseMobileController
{
    public function __construct(
        private ArticleService $articleService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function getArticles(GetArticlesRequest $request): JsonResponse
    {
        return $this->articleService->getArticles($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(ArticleDetailRequest $request): JsonResponse
    {
        return $this->articleService->detail($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function addViewCount(ArticleDetailRequest $request):JsonResponse
    {
        return $this->articleService->addViewCount($request['id']);
    }

}
