<?php

namespace BasicDashboard\Mobile\Categories\Services;

use BasicDashboard\Foundations\Domain\Categories\Repositories\CategoryRepositoryInterface;
use BasicDashboard\Mobile\Categories\Resources\CategoryResource;
use BasicDashboard\Mobile\Common\BaseMobileController;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A CategoryService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CategoryService extends BaseMobileController
{
    const INDEX_SUCCESS = "Index success";
    const DETAIL_SUCCESS = "Detail success";

    public function __construct(
        private CategoryRepositoryInterface $categoryRepository,
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): JsonResponse
    {
        $data = $this->categoryRepository->getCategoryListForMobile();
        $data = CategoryResource::collection($data)->response()->getData(true)['data'];
        return $this->sendResponse(self::INDEX_SUCCESS, $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(array $request): JsonResponse
    {
        try {
            $this->categoryRepository->beginTransaction();
            $data = $this->categoryRepository->edit($request['id']);
            $data = new CategoryResource($data);
            $data = $data->response()->getData(true)['data'];
            $this->categoryRepository->commit();
            return $this->sendResponse(self::DETAIL_SUCCESS, $data);
        } catch (Exception $e) {
            return $this->sendError($e->getMessage());
        }
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
