<?php

namespace BasicDashboard\Foundations\Domain\Countries\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\Countries\Country;
use BasicDashboard\Foundations\Domain\Countries\Repositories\CountryRepositoryInterface;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A CountryRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class CountryRepository extends BaseRepository implements CountryRepositoryInterface
{
    public function __construct(Country $model)
    {
        parent::__construct($model);
    }

    public function filterCountry(array $params): Builder | Country
    {
        $connection = $this->connection();
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('name', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('zip_code', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('country_code', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('currency_code', 'LIKE', '%' . $params['keyword'] . '%')
                ->orWhere('measure_unit', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getCountryList($params): LengthAwarePaginator
    {
        return $this->filterCountry($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }
}
