<?php

namespace BasicDashboard\Web\Subcategories\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateSubcategoryRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateSubcategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name" => "max:255|required",
            "name_other" => "max:255|required",
            "description" => "",
            "description_other" => "",
            "category_id" => "required",
        ];
    }

    public function messages(): array
    {
        return [
            'name.required' => __('subcategory.name_validation'),
            'name_other.required' => __('subcategory.name_other_validation'),
            'description.required' => __('subcategory.description_validation'),
            'description_other.required' => __('subcategory.description_other_validation'),
            'category_id.required' => __('subcategory.category_id_validation'),
        ];
    }
}
