<?php

namespace BasicDashboard\Mobile\Pages\Controllers;

use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Pages\Services\PageService;
use BasicDashboard\Mobile\Pages\Validation\PageDetailRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A PageController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageController extends BaseMobileController
{
    public function __construct(
        private PageService $pageService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->pageService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////


    public function show(PageDetailRequest $request): JsonResponse
    {
        return $this->pageService->show($request->validated()['slug']);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

}
