<?php

namespace BasicDashboard\Web\Categories\Validation;

use Illuminate\Foundation\Http\FormRequest;
use BasicDashboard\Foundations\Domain\Articles\Article;
use Illuminate\Validation\Rule;

/**
 *
 * A DeleteCategoryRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteCategoryRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            // "id" => "required",  
            "id" => [
                'required',
                function ($attribute, $value, $fail) {
                    $categoryID = customDecoder($value);
                    $hasArticles = Article::where('category_id', $categoryID)->exists();
                    if ($hasArticles) {
                        $fail('Cannot delete this category because it has associated articles.');
                    }
                }
            ]

        ];
    }
}
