<?php

namespace BasicDashboard\Mobile\Pages\Services;

use BasicDashboard\Foundations\Domain\Pages\Repositories\PageRepositoryInterface;
use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Pages\Resources\PageResource;
use Exception;
use Illuminate\Http\JsonResponse;

/**
 *
 * A PageService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class PageService extends BaseMobileController
{

    public function __construct(
        private PageRepositoryInterface $pageRepository,
    )
    {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): JsonResponse
    {
        $data = $this->pageRepository->getPageList($request);
        $data = PageResource::collection($data)->response()->getData(true);
        return $this->sendResponse("Index success", $data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $slug): JsonResponse
    {
        $data = $this->pageRepository->showBySlug($slug);
        $data= new PageResource($data);
        $data= $data->response()->getData(true)['data'];
        return $this->sendResponse('Show success',$data);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
