<?php

namespace BasicDashboard\Spa\Articles\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A GetArticlesRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class GetArticlesRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'category_id' => '',
            'subcategory_id' => '',
            'is_banner' => '',
            'is_highlighed' => '',
            'type' => ''
        ];
    }

}
