<?php

namespace BasicDashboard\Mobile\Subcategories\Controllers;

use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\Subcategories\Services\SubcategoryService;
use BasicDashboard\Mobile\Subcategories\Validation\GetSubcategoriesRequest;
use BasicDashboard\Mobile\Subcategories\Validation\SubcategoryDetailRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 *
 * A SubcategoryController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SubcategoryController extends BaseMobileController
{
    public function __construct(
        private SubcategoryService $subcategoryService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function detail(SubcategoryDetailRequest $request): JsonResponse
    {
        return $this->subcategoryService->detail($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function getSubCategories(GetSubcategoriesRequest $request): JsonResponse
    {
        return $this->subcategoryService->getSubCategories($request->validated());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
