<?php

namespace BasicDashboard\Foundations\Domain\Addresses;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use BasicDashboard\Foundations\Domain\Countries\Country;

/**
 *
 * A Address is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class Address extends Model
{
    use HasFactory, SoftDeletes;
      //protected $table = 'table_name';
      protected $guarded = [

    ];

    public function country(): BelongsTo
    {
      return $this->belongsTo(Country::class)->withDefault([
        'name' => '---'
      ]);
    }

}
