<?php

namespace BasicDashboard\Web\Addresses\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreAddressRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreAddressRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "level1_code" => "required",
            "level1_name" => "required",
            "level2_code" => "required",
            "level2_name" => "required",
            "level3_code" => "required",
            "level3_name" => "required",
            "level4_code" => "required",
            "level4_name" => "required",
            "country_id" => "numeric|required",
        ];
    }

    public function messages(): array
    {
        return [
            'level1_code.required' => __('address.level1_code_validation'),
            'level1_name.required' => __('address.level1_name_validation'),
            'level2_code.required' => __('address.level2_code_validation'),
            'level2_name.required' => __('address.level2_name_validation'),
            'level3_code.required' => __('address.level3_code_validation'),
            'level3_name.required' => __('address.level3_name_validation'),
            'level4_code.required' => __('address.level4_code_validation'),
            'level4_name.required' => __('address.level4_name_validation'),
            'country_id.numeric' => __('address.country_id_validation'),
        ];
    }
}