<?php

namespace BasicDashboard\Web\Addresses\Validation;

use Illuminate\Validation\Rule;
use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateAddressRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateAddressRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "level1_code"=>"required",
            "level1_name"=>"required",
            "level2_code"=>"required",
            "level2_name"=>"required",
            "level3_code"=>"required",
            "level3_name"=>"required",
            "level4_code"=>"required",
            "level4_name"=>"required",
            "level5_code"=>"",
            "level5_name"=>"",
            "level6_code"=>"",
            "level6_name"=>"",
            "level7_code"=>"",
            "level7_name"=>"",
            "country_id" => "numeric|required",
        ];
    }

    public function messages(): array
    {
        return[
            'level1_code.required' => __('address.level1_code_validation'),
            'level1_name.required' => __('address.level1_name_validation'),
            'level2_code.required' => __('address.level2_code_validation'),
            'level2_name.required' => __('address.level2_name_validation'),
            'level3_code.required' => __('address.level3_code_validation'),
            'level3_name.required' => __('address.level3_name_validation'),
            'level4_code.required' => __('address.level4_code_validation'),
            'level4_name.required' => __('address.level4_name_validation'),
            'level5_code.required' => __('address.level5_code_validation'),
            'level5_name.required' => __('address.level5_name_validation'),
            'level6_code.required' => __('address.level6_code_validation'),
            'level6_name.required' => __('address.level6_name_validation'),
            'level7_code.required' => __('address.level7_code_validation'),
            'level7_name.required' => __('address.level7_name_validation'),
            'country_id.required' => __('address.country_id_validation'),
        ];
    }
}
