<?php

namespace BasicDashboard\Spa\SponsorAds\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use BasicDashboard\Spa\Common\BaseSpaController;
use BasicDashboard\Spa\SponsorAds\Services\SponsorAdService;
use BasicDashboard\Spa\SponsorAds\Validation\GetSponsorAdRequest;
use BasicDashboard\Spa\SponsorAds\Validation\SponsorAdDetailRequest;



/**
 *
 * A SponsorAdController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SponsorAdController extends BaseSpaController
{
    public function __construct(
        private SponsorAdService $sponsorAdService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->sponsorAdService->index($request->all());
    }


    ///////////////////////////This is Method Divider///////////////////////////////////////
    public function detail(SponsorAdDetailRequest $request): JsonResponse
    {
        return $this->sponsorAdService->show($request->id);
    }


}
