<?php

namespace BasicDashboard\Foundations\Domain\SponsorAds\Providers;

use BasicDashboard\Foundations\Domain\SponsorAds\Repositories\Eloquent\SponsorAdRepository;
use BasicDashboard\Foundations\Domain\SponsorAds\Repositories\SponsorAdRepositoryInterface;
use Illuminate\Support\ServiceProvider;

/**
 *
 * A SponsorAdProvider is bind with Repository and RepositoryInterface.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */


class BindSponsorAdProvider extends ServiceProvider
{
    /**
     * Register services.
     */
    public function register(): void
    {
        $this->app->bind([
            SponsorAdRepository::class,
            SponsorAdRepositoryInterface::class,
        ]);
    }

    /**
     * Bootstrap services.
     */
    public function boot(): void
    {
        //
    }
}
