<?php

namespace BasicDashboard\Foundations\Domain\Sports\Repositories\Eloquent;

use BasicDashboard\Foundations\Domain\Base\Repositories\Eloquent\BaseRepository;
use BasicDashboard\Foundations\Domain\Sports\Repositories\SportRepositoryInterface;
use BasicDashboard\Foundations\Domain\Sports\Sport;
use Illuminate\Contracts\Database\Eloquent\Builder;
use Illuminate\Pagination\LengthAwarePaginator;

/**
 *
 * A SportRepository is includes extra function for implementing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SportRepository extends BaseRepository implements SportRepositoryInterface
{
    public function __construct(Sport $model)
    {
        parent::__construct($model);
    }

    public function filterSport(array $params): Builder | Sport
    {
        $connection = $this->connection();
        if (isset($params['keyword']) && strlen($params['keyword']) > 0) {
            $connection = $connection->where('name', 'LIKE', '%' . $params['keyword'] . '%');
        }
        return $connection;
    }

    public function getSportList($params): LengthAwarePaginator
    {
        return $this->filterSport($params)
            ->orderByRaw('CASE WHEN created_at IS NULL THEN updated_at ELSE created_at END DESC')
            ->orderBy('id', 'desc')
            ->paginate(request()->paginate ?? config('numbers.paginate'));
    }
}
