<?php

namespace BasicDashboard\Spa\ContactForm\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreContactFormRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreContactFormRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name"=>"required",
            "email"=>"required",
            "message"=>"required"
        ];
    }
}
