<?php

namespace BasicDashboard\Web\Audits\Services;

use BasicDashboard\Foundations\Domain\Audits\Repositories\AuditRepositoryInterface;
use BasicDashboard\Web\Audits\Resources\AuditResource;
use BasicDashboard\Web\Common\BaseController;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

/**
 *
 * A AuditService is the manager of methods.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class AuditService extends BaseController
{
    const VIEW = 'admin.audit';

    public function __construct(
        private AuditRepositoryInterface $auditRepository,
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(array $request): View
    {
        $auditList = $this->auditRepository->getAuditList($request);
        $auditList = AuditResource::collection($auditList)->response()->getData(true);
        return $this->returnView(self::VIEW . ".index", $auditList, $request);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function show(string $id): View | RedirectResponse
    {
        $audit = $this->auditRepository->show($id);
        $audit = new AuditResource($audit);
        $audit = $audit->response()->getData(true)['data'];
        return $this->returnView(self::VIEW . '.show', $audit);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////
}
