<?php

namespace BasicDashboard\Web\SponsorAds\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A DeleteSponsorAdRequest is responsible validation of id while deleting.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class DeleteSponsorAdRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "id" => "required",
        ];
    }
}
