<?php

namespace BasicDashboard\Web\SponsorAds\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateSponsorAdRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateSponsorAdRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "name" => "required",
            "thumbnail_image" => "",
            "start_date" => "required",
            "end_date" => "required",
            "status" => "",
            "position" => ["required_if:platform,Web"],
            "countSponsorrate" => "",
            "link" => "",
            "size" => "",
            "uploaded_video" => "",
            "description" => "",
            "platform" => "required",
        ];
    }
    public function messages(): array
    {
        return [
            'name.required' => __('sponsorAd.ad_name_validation'),
            'thumbnail_image.required' => __('sponsorAd.ad_photo_validation'),
            'position.required' => __('sponsorAd.position_validation'),
            'start_date.required' => __('sponsorAd.start_date_validation'),
            'end_date.required' => __('sponsorAd.end_date_validation'),
            'platform.required' => __('sponsorAd.platform_validation'),
        ];
    }
    public function all($keys = null)
    {
        $data = parent::all($keys);
        return collect($data)->except(['input_video', '_token'])->toArray();
    }
}
