<?php

namespace BasicDashboard\Mobile\Notifications\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A NotificationRequest is responsible validation of id while calling notification api.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class NotificationDetailRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
          "id"=>"required",
        ];
    }
}
