<?php

namespace BasicDashboard\Web\Subcategories\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SubcategoryResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SubcategoryResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" => customEncoder($this->id),
            "name" => $this->name,
            "description" => $this->description,
            "category" => $this->category->name,
        ];
    }
}
