<?php

namespace BasicDashboard\Web\Notifications\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A StoreNotificationRequest is responsible validation of while storing.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class StoreNotificationRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "title" => "required",
            "body" => "required",
            "sending_method" => "required",
            "sending_date" => "",
        ];
    }

    public function messages()
    {
        return[
            'title.required' => __('notification.title_validation'),
            'body.required' => __('notification.body_validation'),
            'uploaded_photo.required' => __('notification.uploaded_photo_validation'),
            'uploaded_video.required' => __('notification.uploaded_video_validation'),
            'sending_method.required' => __('notification.sending_method_validation'),
            'sending_date.required' => __('notification.sending_method_validation'),
        ];
    }

    public function all($keys = null)
    {
        $data = parent::all($keys);
        return collect($data)->except(['input_video','_token'])->toArray();
    }

    
}
