<?php

namespace BasicDashboard\Web\Notifications\Validation;

use Illuminate\Foundation\Http\FormRequest;

/**
 *
 * A UpdateNotificationRequest is responsible validation of while updating.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class UpdateNotificationRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            "title" => "required",
            "body" => "required",
            "uploaded_photo" => "",
            "uploaded_video" => "",
            "sending_method" => "required",
            "sending_frequency" => "",
            "sending_interval" => ""
        ];
    }

    public function messages(): array
    {
        return [
            'title.required' => __('notification.title_validation'),
            'body.required' => __('notification.body_validation'),
            'uploaded_photo.required' => __('notification.uploaded_photo_validation'),
            'uploaded_video.required' => __('notification.uploaded_video_validation'),
            'sending_method.required' => __('notification.sending_method_validation'),
        ];
    }
    public function all($keys = null)
    {
        $data = parent::all($keys);
        if($data['sending_method']==='Manual'){
            $data['sending_frequency'] = null;
        }        
        return collect($data)->except(['input_video', '_token'])->toArray();
    }
}
