<?php

namespace BasicDashboard\Web\Sports\Resources;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 *
 * A SportResource is implement for sending data with requirements of desire template.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SportResource extends JsonResource
{
    public function toArray($request):array
    {
         return [
            "id" =>customEncoder($this->id),
            "name"=>$this->name,
            "slug"=>$this->slug,
            "image"=>$this->image ? Storage::url($this->image):null,
            "status"=>$this->status,
            "date"=>$this->date,
            "time"=>$this->time,
            "description"=>$this->description,
            "link"=>$this->link,
        ];
    }
}
