<?php

namespace BasicDashboard\Foundations\Domain\Sports;

use App\Enums\SportStatus;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;


/**
 *
 * A Sport is gives a basic way to do that using Eloquent ORM where each table incorporates to interact with it.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */
//if you want to audit this model uncomment below code and import
//#[ObservedBy([AuditObserver::class])]
class Sport extends Model
{
    use HasFactory;
    protected $casts = [
        'status' => SportStatus::class,  
    ];
      //protected $table = 'table_name';
      protected $guarded = [

    ];

}
