<?php

namespace BasicDashboard\Mobile\SponsorAds\Controllers;

use BasicDashboard\Mobile\Common\BaseMobileController;
use BasicDashboard\Mobile\SponsorAds\Services\SponsorAdService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;



/**
 *
 * A SponsorAdController is responsible for receive request and return response.
 * Generated By Custom Artisan Cmd
 * @author Nay Ba la
 * https://github.com/naybala
 * https://naybala.netlify.app/
 *
 */

class SponsorAdController extends BaseMobileController
{
    public function __construct(
        private SponsorAdService $sponsorAdService
    ) {
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

    public function index(Request $request): JsonResponse
    {
        return $this->sponsorAdService->index($request->all());
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////


    public function show(string $id): JsonResponse
    {
        return $this->sponsorAdService->show($id);
    }

    ///////////////////////////This is Method Divider///////////////////////////////////////

}
